spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

eureka:
  instance:
    hostname: springcloud-gateway.herokuapp.com
  client:
    service-url:
#      defaultZone: http://localhost:8761/eureka/
      defaultZone: https://eureka-unialfa.herokuapp.com/eureka/
    healthcheck: true
debug: true
#trace: true
